/** 列表的模拟数据 */
export const TableDemoData = [
  {
    id: 1,
    username: '张三',
    score: 85,
    gender: '1',
    age: 25,
    hobby: ['1', '2'],
    skill: ['3'],
    birthday: '1998-01-01',
  },
  {
    id: 2,
    username: '李四',
    score: 75,
    gender: '2',
    age: 22,
    hobby: ['2'],
    skill: ['4'],
    birthday: '2000-05-05',
  },
  {
    id: 3,
    username: '王五',
    score: 92,
    gender: '1',
    age: 27,
    hobby: ['1', '3'],
    skill: ['1'],
    birthday: '1996-07-15',
  },
  {
    id: 4,
    username: '赵六',
    score: 68,
    gender: '2',
    age: 21,
    hobby: ['3', '4'],
    skill: ['2'],
    birthday: '2001-11-20',
  },
  {
    id: 5,
    username: '孙七',
    score: 88,
    gender: '1',
    age: 26,
    hobby: ['2', '3'],
    skill: ['3'],
    birthday: '1997-03-10',
  },
  {
    id: 6,
    username: '周八',
    score: 72,
    gender: '2',
    age: 23,
    hobby: ['1', '4'],
    skill: ['4'],
    birthday: '1999-08-25',
  },
  {
    id: 7,
    username: '吴九',
    score: 95,
    gender: '1',
    age: 24,
    hobby: ['1'],
    skill: ['1', '2'],
    birthday: '1998-12-01',
  },
  {
    id: 8,
    username: '郑十',
    score: 65,
    gender: '2',
    age: 20,
    hobby: ['2', '3'],
    skill: ['3'],
    birthday: '2002-04-18',
  },
  {
    id: 9,
    username: '钱十一',
    score: 80,
    gender: '1',
    age: 28,
    hobby: ['3'],
    skill: ['2', '4'],
    birthday: '1995-06-12',
  },
  {
    id: 10,
    username: '沈十二',
    score: 78,
    gender: '2',
    age: 22,
    hobby: ['4'],
    skill: ['1'],
    birthday: '2000-10-05',
  },
  {
    id: 11,
    username: '韩十三',
    score: 90,
    gender: '1',
    age: 26,
    hobby: ['1', '2'],
    skill: ['3'],
    birthday: '1997-02-20',
  },
  {
    id: 12,
    username: '杨十四',
    score: 70,
    gender: '2',
    age: 23,
    hobby: ['3', '4'],
    skill: ['4'],
    birthday: '1999-09-15',
  },
];

/** 字典的模拟数据 */
export const DemoDicts = {
  gender: [
    { label: '男', value: '1' },
    { label: '女', value: '2' },
  ],
  hobby: [
    { label: '篮球', value: '1' },
    { label: '足球', value: '2' },
    { label: '乒乓球', value: '3' },
    { label: '羽毛球', value: '4' },
  ],
  skill: [
    { label: '编程', value: '1' },
    { label: '画画', value: '2' },
    { label: '音乐', value: '3' },
    { label: '舞蹈', value: '4' },
  ],
};
